edamontology/edamontology

EDAM_1.12_dev.owl
Please update the resource URI accordingly. I checked the file, and the URI should not be used, but not sure what's there in other active dev branches...
=> Added GPML, the format used by WikiPathways

.github/ISSUE_TEMPLATE/new-format.md
it was not clear to me that the instructions can be removed as the other sentences state to not touch anything else :)
=> the instructions can be removed

EDAM_dev.owl
@matuskalas please review and let's discuss what's missing here!
=> Adding Open science/Data management/FAIR topics (#581)

CONTRIBUTING.md, README.md, changelog.md
I didn't not add instructions because I couldn't give any examples as you did in the other instructions and wasn't sure about the terminology. I'll gladly add instructions when I know what is relevant to them.
=> Type-dependent relationships added to Templates

EDAM_dev.owl
replaced oboInOwl:comment  to rdfs:comment #667
=> Replaced all oboInOwl:comment to rdfs:comment in EDAM_dev.owl

EDAM-logo-square.svg
following recommendation done in https://github.com/edamontology/edamontology/issues/666#issuecomment-827151291
rectangle is missing, but my goal is to make it available, not propose new visuals
P.S: I converted the png into svg with inkscape, nothing else
=> Add current edam logo

EDAM_dev.owl
=> Edited wikipedia links by adding rdf:resource to links which lacked 

EDAM_dev.owl
I have added a new topic for EEG in the EDAM Ontology. The content was provide by @Kigaard and @matuskalas . 
@matuskalas  please review the file and tell me is there any change needed or not.
=> added concept for Electoencephalography

EDAM_dev.owl
I have modified the `EDAM_dev.owl` file of edamontology repository. 
I have added the format concept of "PETab" in the `EDAM_dev.owl` file, keeping in view all the instructions mentioned in the `CONTRIBUTING.md` file to add a new concept. 
@matuskalas kindly review my PR and let me know if any improvements are needed. 
Thank you.
=> Added: New format concept for PETab

.gitattributes, EDAM_dev.owl
I have added two concepts for  Electrocardiography(issue #607) and Cryogenic electron microscopy (issue #687).
the content was provided by @Kigaard.
Also as per issue #682 , I have added logo and repository source in owl file.
@matuskalas  I have closed the previous PR and added both issues in this PR. Review it and tell me is there any change required or not. 😊
=> Added topic concepts for Electrocardiography(#607) and Cryogenic electron microscopy (#687),added logo and repository source in owl file(#682)

EDAM_dev.owl
This PR concludes the work of @slaurie #627 and @melibleq #662.
=> Added gVCF and updated VCF

EDAM_dev.owl
Fixes edamontology/edamontology#705
=> Added missing onProperty is_format_of

.github/workflows/tests-edam2json.yml
In order to highligh errors in the ontology, and/or edam2json
Need #705 to be solved to have error-less CI
=> Test conversion on dev version of the ontology

EDAM_dev.owl
resolve #707 
@matuskalas @bryan-brancotte
=> fixed wrong URL for logo in EDAM_dev.owl

.githooks/pre-commit
Adding user output messages to the pre-commit hook.
=> Fix pre-commit hook (issue #696)

releases/EDAM_1.24.owl
Fixes https://github.com/edamontology/edamontology/issues/723.
=> Small fix to the 1.24 release OWL file

EDAM_dev.owl
Changes in the Docker image format, as requested in https://github.com/edamontology/edamontology/issues/563.
=> Fixes Docker image format

EDAM_dev.owl
Fixed Environmental science(s):
- Moved from Biology (bug) to top-level Topic
- Changed Environment synonym to related term
- Changed to plural sciences
Added new high-level topic Biosciences
Moved bio-related high-level topics underneath Biosciences
Fixed Ecology by moving it directly under Biosciences and Environmental sciences
=> Minor refactoring of broad topics: Biosciences, Environmental science(s), and Ecology

EDAM_dev.owl
Broad synonyms "life science" and "life sciences" from biology (topic_3070)
FIX #754
=> remove Life science synonym from biology topic

EDAM_dev.owl
@matuskalas please review so I can figure out if what I did is correct
=> Added carbon cycle topic

EDAM_dev.owl
topic_3339 -  Microbial collection
topic_0166 - Protein structural motifs and surfaces
topic_1775 - Function analysis
topic_3576 - Medical biotechnology
=> Added 3 wikipedia links

EDAM_dev.owl
* Edits to BCF format: added documentation link and file extensions (issue #697)
* Added format cml (issue #721)
* Added format cif (issue #720)
* Added tag (topic) "ribosome profiling" (issue #410)
* Added BioSimulators format for the specifications of biosimulation tools (issue #590)
* Added format BioSimulators standard for command-line interfaces for biosimulation tools (issue #591)
* Added data identifier "ORCID identifier" (issue #594)
=> Updates EDAM_dev.owl

EDAM_dev.owl
Add "Microfludics" (Fix #743)
Adds "Acoustics" (Fix #744)
Adds "Single-cell sequencing" (Fix #774)
=> Add new terms

EDAM_dev.owl
http://edamontology.org/operation_3803 | oboInOwl:hasBroadSynonym | Metabolite identification
http://edamontology.org/operation_3803 | oboInOwl:hasNarrowSynonym | Metabolite identification
http://edamontology.org/topic_0780 | oboInOwl:hasBroadSynonym | Plant science
http://edamontology.org/topic_0780 | oboInOwl:hasExactSynonym | Plant science
http://edamontology.org/topic_3174 | oboInOwl:hasBroadSynonym | Biome sequencing
http://edamontology.org/topic_3174 | oboInOwl:hasNarrowSynonym | Biome sequencing
Duplicated synonyms were removed
=> Duplicate scoped synonym removed

EDAM_dev.owl
=> Fixing formating error (eol in annotation)

.github/workflows/robot_reason_report.yml, .github/workflows/test_wikipedia_links.yml, EDAM_dev.owl
Added ROBOT workflow file
new file .github/workflow/robot_reason_report.yml
Calling robot reason and robot report
=> Validation - ROBOT workflow + wikipedia missing link workflow

EDAM_dev.owl
for is_refactor_candidate and isdebtag annotation
=> Boolean datatype updated 

EDAM_dev.owl
Partially fixes problems from Issue #815.
=> Corrected duplicate_exact_synonym raised errors

EDAM-logo-rectangle.svg, EDAM-logo-square.svg
While waiting on a decision for the logi (cf https://github.com/edamontology/logoi) I propose that we update the logo form the same as they were is order to have a better looking logo available here, and used in the browser.
=> Update logo : real svg, less blurry.

EDAM_dev.owl
Adds "Power Test" (Fix #757).
Adds operation "DNA modification prediction" (Fix #759).
Adds operation "Disease transmission analysis" (Fix #760).
Adds operation "Multiple testing correction" (Fix #762 & closes #761).
Add formats PQR and PDBQT (Confer #239)
=> Add terms (December 2021)

EDAM_dev.owl
Update the operation **http://edamontology.org/operation_0256** (Fix #780)
Instead of inputs **data_0849** and **data_1270**, expected input should be **data_1255**.
=> Update "has_input" property of "operation_0256" (#780)

EDAM_dev.owl
ORCID start and end of line deleted
GEO accession number updated with different prefixes
OMIM regex validated + added documentation to explain prefixes
FIX #800
=> ^ in Regex ID

EDAM_dev.owl
Removed whit space at the en of concept 4034 definition
=> Fixed robot warning

EDAM_dev.owl
=> Merging DM concepts etc. from WebProtégé

EDAM_dev.owl
with either 4 spaces or removed them (following the OWLAPI style)
=> Replaced tab characters

EDAM_dev.owl
- narrow: Research data management (RDM)
- related terms: Research data life cycle (also spelled together, see https://en.wiktionary.org/wiki/life_cycle#English)
Note: https://en.wikipedia.org/wiki/Research_data_lifecycle is a redirect to https://en.wikipedia.org/wiki/Data_management
=> Added synonym & related terms for DM

CONTRIBUTING.md
- order of attributes corresponding to OWLAPI (like from WebProtégé)
- added some attributes (todo more)
- review all (todo)
- sync (make same) as the templates in WebProtégé (todo)
Is still not perfect, but getting there...
=> Updated templates for concepts (in CONTRIBUTING.md)

EDAM_dev.owl
=> Added software management concepts. Polished data curation, management, etc.

EDAM_dev.owl
=> Add Nextflow and Snakemake formats.

EDAM_dev.owl
Added attribute "subClassOf" textual format
=> Add attribute subClassOf to concepts Snakemake and Nextflow

EDAM_dev.owl
=> Sdrf format new PR

changelog-detailed.md
The tables were generated using a python script and OpenRefine. The python script is "reformatting_edam_matches_table_from_openrefine.py" in (https://github.com/edamontology/scripts).
=>  Added tables for skos matches of EDAM concepts

EDAM_dev.owl
ChIP-exo subClassOf topic Sequencing
Hi-C subClassOf topic Chromosome conformation capture
ATAC-seq subClassOf topic Chromosome conformation capture
Required for genomics collaboration project
=> Add topics related to HTS techniques

EDAM_dev.owl
fixes #911 (part of)
added attributes to format_3616 "tabix", changed parent class from "Image format" to "Data index format"
deprecated format_3700 "Tabix index file format"
=> Tabix format issues

EDAM_dev.owl
Added definition to concept "RNAi experiment":
"Experiment in which the expression of a specific gene is post-transcriptionally knocked down or silenced by means of a small RNA (sRNA) causing the degradation of the gene transcript (mRNA), and thus preventing the production of the corresponding protein."
Added new children classes "miRNA silencing" and "siRNA experiment"
* [Data acquisition]
* [RNAi experiment]
* miRNA sliencing
* siRNA experiment
=> Added topics miRNA silencing and siRNA experiment
